"""
kaggle_finetune.py
==================
Fine-tuning script for the NIFTY signal pod.
Designed to run as a Kaggle notebook on free-tier T4 GPU.

MODEL CHOICE: TinyLlama-1.1B-Chat-v1.0
Rationale:
  - 1.1B parameters fits comfortably in T4 VRAM (15GB) even with LoRA + 16-bit
  - Chat variant ships with a working instruction template (ChatML-style)
  - Phi-2 (2.7B) was considered but requires more VRAM and the task is
    structured-output formatting, not reasoning depth — TinyLlama is sufficient
  - TinyLlama's smaller footprint means faster iteration within 30hr/week limit

LORA CONFIG: rank=8
Rationale:
  - rank 4 is minimal; rank 16 adds parameters without clear benefit for
    a 300-sample dataset.  rank 8 balances expressivity vs. overfitting risk.
  - alpha=16 (2x rank) is a standard starting point; reduces step size noise.
  - target_modules: q_proj, v_proj (standard attention LoRA targets)
  - dropout=0.05 for light regularisation on a small dataset

CONVICTION DESIGN:
  The conviction field is a *text token* generated by the model, not a
  softmax probability.  It is meaningful because:
  (a) the training data contains conviction values correlated with regime strength
  (b) we evaluate calibration post-hoc (slope of conviction vs binary correctness)
  (c) the orchestrator uses it as a filter (< 0.40 → downgrade)
  softmax over the direction token would measure only token-level uncertainty,
  not alignment between regime conditions and historical outcomes.

Usage on Kaggle:
  1. Upload cleaned_finetune_instructions.jsonl as a dataset
  2. Run this script as a notebook (GPU T4 x2, or single T4)
  3. Adapter weights saved to /kaggle/working/nifty_signal_pod/
  4. Download and place in signal_pod/adapters/nifty_signal_pod/
"""

# ── 0. Kaggle environment setup ───────────────────────────────────────────────
import os, sys
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# Install dependencies (Kaggle pip install)
# os.system("pip install -q peft bitsandbytes accelerate datasets mlflow")

# ── 1. Imports ────────────────────────────────────────────────────────────────
import json
import math
import uuid
from pathlib import Path
from datetime import datetime, timezone

import torch
import mlflow
import mlflow.pytorch
import numpy as np
from datasets import Dataset
from peft import LoraConfig, TaskType, get_peft_model, PeftModel
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)

# ── 2. Paths ──────────────────────────────────────────────────────────────────
INPUT_DATA = Path("/kaggle/input/nifty-slm-data/cleaned_finetune_instructions.jsonl")
OUTPUT_DIR = Path("/kaggle/working/nifty_signal_pod")
MLFLOW_DIR = Path("/kaggle/working/mlruns")

BASE_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# ── 3. MLflow — must be initialised BEFORE any training ──────────────────────
mlflow.set_tracking_uri(str(MLFLOW_DIR))
mlflow.set_experiment("nifty_signal_pod")

# ── 4. Load cleaned data ──────────────────────────────────────────────────────
print(f"Loading data from {INPUT_DATA}")
raw_records = [json.loads(l) for l in INPUT_DATA.read_text().splitlines() if l.strip()]
print(f"  Records loaded: {len(raw_records)}")

# Shuffle with fixed seed for reproducibility
rng = np.random.default_rng(42)
indices = rng.permutation(len(raw_records))
raw_records = [raw_records[i] for i in indices]

# ── 5. Tokenizer & prompt formatting ─────────────────────────────────────────
print(f"Loading tokenizer: {BASE_MODEL}")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, use_fast=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

MAX_LENGTH = 512

def format_example(record: dict) -> str:
    """
    TinyLlama ChatML format.
    The model learns to generate the JSON output given the system prompt + input.
    """
    system = record["instruction"]
    user_msg = record["input"]
    assistant_msg = record["output"]
    return (
        f"<|system|>\n{system}</s>\n"
        f"<|user|>\n{user_msg}</s>\n"
        f"<|assistant|>\n{assistant_msg}</s>"
    )

def tokenize(example: dict):
    full_text = format_example(example)
    encoded = tokenizer(
        full_text,
        max_length=MAX_LENGTH,
        truncation=True,
        padding="max_length",
    )
    # For causal LM we shift labels; mask the prompt tokens with -100
    # Find where assistant response starts
    prompt_only = (
        f"<|system|>\n{example['instruction']}</s>\n"
        f"<|user|>\n{example['input']}</s>\n"
        "<|assistant|>\n"
    )
    prompt_enc = tokenizer(prompt_only, add_special_tokens=False)
    prompt_len = len(prompt_enc["input_ids"])

    labels = list(encoded["input_ids"])
    labels[:prompt_len] = [-100] * prompt_len
    encoded["labels"] = labels
    return encoded

print("Tokenizing dataset …")
dataset = Dataset.from_list(raw_records)
tokenized = dataset.map(tokenize, remove_columns=dataset.column_names)
print(f"  Tokenized rows: {len(tokenized)}")

# ── 6. Load base model (4-bit) ────────────────────────────────────────────────
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

print("Loading base model …")
model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
)
model.config.use_cache = False
model.config.pretraining_tp = 1
print(f"  Base model loaded. Params: {sum(p.numel() for p in model.parameters()):,}")

# ── 7. LoRA configuration ─────────────────────────────────────────────────────
# rank=8: balances expressivity vs overfitting on 300 samples
# alpha=16: 2x rank, standard conservative choice
# target q_proj + v_proj: sufficient for structured-output tasks
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    target_modules=["q_proj", "v_proj"],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
# Expected: ~0.5% trainable parameters

# ── 8. Training arguments ─────────────────────────────────────────────────────
training_args = TrainingArguments(
    output_dir=str(OUTPUT_DIR),
    num_train_epochs=5,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,          # effective batch = 16
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    report_to="none",                        # we use MLflow manually
    dataloader_num_workers=0,
    seed=42,
    group_by_length=True,
)

# ── 9. Trainer ────────────────────────────────────────────────────────────────
data_collator = DataCollatorForSeq2Seq(
    tokenizer, model=model, padding=True, pad_to_multiple_of=8
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized,
    data_collator=data_collator,
)

# ── 10. Train with MLflow logging ─────────────────────────────────────────────
with mlflow.start_run(run_name=f"lora_r8_alpha16_epoch5_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S')}") as run:
    mlflow.log_params({
        "base_model": BASE_MODEL,
        "lora_rank": 8,
        "lora_alpha": 16,
        "lora_dropout": 0.05,
        "target_modules": "q_proj,v_proj",
        "num_epochs": 5,
        "batch_size": 4,
        "grad_accum": 4,
        "learning_rate": 2e-4,
        "lr_scheduler": "cosine",
        "max_length": MAX_LENGTH,
        "train_rows": len(tokenized),
        "conviction_design": "text_token_not_softmax",
    })

    print("Starting training …")
    train_result = trainer.train()
    metrics = train_result.metrics

    mlflow.log_metrics({
        "train_loss": metrics.get("train_loss", 0),
        "train_runtime_s": metrics.get("train_runtime", 0),
        "train_samples_per_second": metrics.get("train_samples_per_second", 0),
    })

    mlflow.log_param("mlflow_run_id", run.info.run_id)
    print(f"Training complete. Loss: {metrics.get('train_loss', 'N/A'):.4f}")

# ── 11. Save adapter weights ──────────────────────────────────────────────────
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
model.save_pretrained(str(OUTPUT_DIR))
tokenizer.save_pretrained(str(OUTPUT_DIR))
print(f"Adapter saved → {OUTPUT_DIR}")

# ── 12. Quick sanity-check inference ─────────────────────────────────────────
print("\nRunning sanity-check inference …")
model.eval()
test_prompt = (
    "<|system|>\nYou are a trading signal generator for NIFTY 50 options. "
    "Analyze the provided market state snapshot and generate a structured trading signal. "
    'Return ONLY valid JSON matching the required schema. Schema: {"direction": "CE"|"PE"|"NEUTRAL", '
    '"conviction": float 0.0-1.0, "horizon": "intraday"|"next_session", '
    '"signal_id": string, "generated_at": string}</s>\n'
    '<|user|>\n{"nifty_spot": 23100.0, "atm_iv": 14.5, "iv_skew_25d": 1.2, '
    '"pcr": 1.05, "adx_14": 25.0, "realized_vol_5d": 11.0, '
    '"vix_india": 16.0, "dte_nearest": 3, "moneyness_band": "ATM"}</s>\n'
    "<|assistant|>\n"
)
inputs = tokenizer(test_prompt, return_tensors="pt").to(model.device)
with torch.no_grad():
    out = model.generate(
        **inputs, max_new_tokens=100, temperature=0.1,
        do_sample=False, pad_token_id=tokenizer.pad_token_id
    )
raw = tokenizer.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
print("Sanity check output:", raw.strip())

# Validate JSON
try:
    parsed = json.loads(raw.strip())
    print("JSON parse: OK")
    print("direction:", parsed.get("direction"))
    print("conviction:", parsed.get("conviction"))
except json.JSONDecodeError as e:
    print("JSON parse FAILED:", e)
    print("(This means model needs more fine-tuning or prompt adjustment)")

print("\nDone. Upload nifty_signal_pod/ folder to repo.")
